/// <reference types="@sveltejs/kit" />
/// <reference lib="webworker" />

declare let self: ServiceWorkerGlobalScope;

import { build, files, prerendered, version } from '$service-worker';

// Create a unique cache name based on the deployment version
const CACHE_NAME = `cache-${version}`;

// Create a list of all application assets to cache
const ASSETS = [
	...build, // the app's compiled JS/CSS
	...files, // everything in the static directory
	...prerendered // all prerendered pages and data (essential for offline HTML)
];

self.addEventListener('install', (event) => {
	// Create a new cache and add all files to it to optimise offline loading
	async function addFilesToCache() {
		const cache = await caches.open(CACHE_NAME);
		await cache.addAll(ASSETS);
	}

	event.waitUntil(addFilesToCache());
});

self.addEventListener('activate', (event) => {
	// Remove previous cached data from disk to free up space
	async function deleteOldCaches() {
		for (const key of await caches.keys()) {
			if (key !== CACHE_NAME) {
				await caches.delete(key);
			}
		}
	}

	event.waitUntil(deleteOldCaches());
});

self.addEventListener('fetch', (event) => {
	// Only handle GET requests
	if (event.request.method !== 'GET') return;

	async function respond() {
		const url = new URL(event.request.url);
		const cache = await caches.open(CACHE_NAME);

		// Assets generated by the build process, in the static directory,
		// or prerendered pages can always be safely served from the cache
		if (ASSETS.includes(url.pathname)) {
			const cachedResponse = await cache.match(event.request);
			if (cachedResponse) {
				return cachedResponse;
			}
		}

		// For everything else, try the network first, but
		// fall back to the cache if we are offline
		try {
			const response = await fetch(event.request);

			// If the network request is successful, clone the response and cache it
			if (response.status === 200) {
				cache.put(event.request, response.clone());
			}

			return response;
		} catch (error) {
			// If the network request fails (e.g., offline behaviour), try serving from cache
			const cachedResponse = await cache.match(event.request);
			if (cachedResponse) {
				return cachedResponse;
			}

			// If navigating offline and the specific page isn't in the cache,
			// fall back to the root application shell to allow client-side routing to take over
			if (event.request.mode === 'navigate') {
				const rootResponse = await cache.match('/');
				if (rootResponse) {
					return rootResponse;
				}
			}

			throw error;
		}
	}

	event.respondWith(respond());
});
